Fixes #1271 remove blanks before anchors in titles
Open-Systems-Pharmacology/OSPSuite.ReportingEngine pull request #1272
Opened 2024-09-03 14:00 UTC by pchelle

2024-09-03 16:03 UTC, Yuri05 approved these changes

2024-09-03 16:03 UTC, Yuri05 commented
@pchelle 8 tests failed...

2024-09-03 16:04 UTC, Yuri05 requested changes
fix failinbg tests

2024-09-04 10:17 UTC, pchelle commented
> fix failing tests

Fixed now :)

2024-09-04 10:48 UTC, Yuri05 approved these changes

2024-09-04 10:48 UTC, merged