558 digits
Open-Systems-Pharmacology/OSPSuite.ReportingEngine pull request #559
Opened 2021-09-28 12:48 UTC by pchelle

2021-09-28 13:32 UTC, msevestre requested changes
Also I can't seem to find where sprintf is being used in the diff

2021-09-28 13:32 UTC, msevestre commented on tests/data/mean-pk/A-pkAnalysis.csv
> +"Organism|A|Concentration in container","C_max",2.85,"µmol/l"
Hum... Why are those values truncated? Number  of digits is only a display artefact not an `export` artefact. This looks suspicious to me

2021-09-28 13:32 UTC, msevestre commented on tests/data/pop-pk/Plasma-AUC_tEnd-ratio.csv
> +"Pediatric",100,1.47,1.38,1.39,1.39,1.46,1.39,1.44,1.39,0.99
same here. Table should be exported using full digits IMO
@Yuri05 thoughts?

2021-09-29 12:02 UTC, pchelle commented on R/utilities-writing-report.R
> +    )
@msevestre `formatNumerics` is now applied only when added to the .md report.
The results exported in .csv have all the necessary digits.
Also, let me know if I should expose the `formatNumerics` method (which is now different from what is implemented in `ospsuite` package with no need for `nsmall`)

2021-09-29 18:51 UTC, msevestre commented
@pchelle ok going to merge this. I can't believe that we have to write such code to format digit properly in R to be honest
We have such a function in .NET and we should expose it via ospsuite-r instead. Good enough for now

2021-09-29 18:52 UTC, merged